# Docker Compose reference guide at https://docs.docker.com/go/compose-spec-reference/

# create docker volumes via
# docker volume create file-data 
# docker volume create db-data

#For examples, see the Awesome Compose repository: https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test: curl --fail http://localhost/api/v1/healthcheck || exit 1
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - 80:80
      - 8080:8080
    depends_on:
       db:
         condition: service_healthy
    networks:
      - frontend
      - backend
    read_only: true   # container to be created with a read-only filesystem
    tmpfs:            # temporary file systems inside the container
      - /tmp
    volumes:
      - file-data:/usr/src/app/.remote

  db:
    image: mongo:jammy
    restart: always
    healthcheck:
      test: echo 'db.stats().ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - '27017:27017'
    networks:
      - backend
    read_only: true   # container to be created with a read-only filesystem
    tmpfs:            # temporary file systems inside the container
      - /tmp
    volumes:
      - db-data:/data/db

# secrets:
#   db-password:
#     file: db/password.txt
volumes:
  file-data:
  db-data:

networks:
  frontend:
  backend:
    internal: true    # disable egress


